### ISSUE TITLE
Tracking issue: Backend MVP

### ISSUE THREAD

**Issue by bakaq** [bakaq/market-helper#1]
- [x] CRUD
  - [X] Get all items.
  - [X] Add an item.
  - [x] Update an item.
  - [x] Remove an item.
- [x] Use an actual database (SQLite will probably be good enough to start)

Out of scope for MVP:

- "Authentication" of users so that the items aren't all public.
- Production database.
- Serverless.
- Deployment.
