### ISSUE TITLE
Tracking issue: Frontend MVP

### ISSUE THREAD

**Issue by bakaq** [bakaq/market-helper#2]
- [x] CRUD
  - [x] Show list of items.
  - [x] Sort items by nutrition price.
  - [x] Add item.
  - [x] Update item.
  - [x] Remove item.
- [x] Usable in phone.

Out of scope for MVP:

- Good UI.
- "Authentication" "sessions" so that items aren't all public.
- Deployment.
